# Heather: a soft theme for Calm Terminal, in light and dark.
name = "Heather"

[dark]
background = "#221c22"
foreground = "#c4bac5"
cursor = "#c3a7c0"
selection = "#3a333a"
palette = "#373037, #c68e88, #83aa84, #ae9e6c, #81a1ca, #b88fb3, #67acac, #b7aeb7, #776e77, #e0a29c, #97c197, #c5b37d, #94b7e4, #d0a3cb, #78c4c3, #dad1da"
sidebar = "#1c161c"
accent = "#c59bc0"

[light]
background = "#f8f2f8"
foreground = "#504b50"
cursor = "#62495f"
selection = "#dcd7dc"
palette = "#4a464a, #955954, #4d784f, #7c6a31, #4b6e99, #865b82, #227a7a, #d4cfd4, #837e83, #844642, #3a673c, #6c5918, #385c8a, #754871, #00696a, #ebe6eb"
sidebar = "#f0ebf0"
accent = "#8f638b"
